name = "wikitown"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "wikitown-db"
database_id = "5f572aa3-4629-48ef-9010-4b9b542c232e"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "wikitown-media"
